env_name: cartpole
output_dir: runs

puffer:
  slowly: true
  checkpoint_dir: runs/checkpoints
  checkpoint_interval: 200
  log_dir: runs/logs
  train:
    data_dir: runs/pufferlib
    gpus: 1
    total_timesteps: 10000000
    minibatch_size: 8192
    horizon: 64
  vec:
    total_agents: 4096
    num_buffers: 2
    num_threads: 16
  env:
    num_envs: 4
  policy:
    hidden_size: 32
    num_layers: 2
    expansion_factor: 1
  sweep:
    max_runs: 3
    gpus: 1
    use_gpu: true
    metric: score
    downsample: 1
    sweep_only: total_timesteps,horizon,minibatch_size,learning_rate,ent_coef,gamma,total_agents,num_buffers,hidden_size
    train:
      total_timesteps:
        distribution: log_normal
        min: 5000000
        max: 20000000
        scale: time
      horizon:
        distribution: uniform_pow2
        min: 64
        max: 256
        scale: auto
      minibatch_size:
        distribution: uniform_pow2
        min: 4096
        max: 65536
        scale: auto
      learning_rate:
        distribution: log_normal
        min: 0.00001
        max: 0.1
        scale: 0.5
      ent_coef:
        distribution: log_normal
        min: 0.00001
        max: 0.2
        scale: auto
      gamma:
        distribution: logit_normal
        min: 0.8
        max: 0.9999
        scale: auto
      clip_coef:
        distribution: uniform
        min: 0.05
        max: 0.5
        scale: auto
    vec:
      total_agents:
        distribution: uniform_pow2
        min: 4096
        max: 16384
        scale: auto
      num_buffers:
        distribution: int_uniform
        min: 1
        max: 8
        scale: auto
    policy:
      hidden_size:
        distribution: uniform_pow2
        min: 32
        max: 1024
        scale: auto
